### ISSUE TITLE
Match school count between EMS and Unified DB for GKA Dashboard

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#146]
@brijeshpoojary @shivangi @ansal

**Comment by shivangi** [comment]
What school count? @menakakhare ?

**Comment by menakakhare** [comment]
This was regarding the pending GKA schools which was missing in Unified DB. @brijeshpoojary  is yet to port these schools to unified DB . Further these schools have to be tagged for GKA in unified DB by @shivangi .

**Comment by shivangi** [comment]
@brijeshpoojary is this done?

**Comment by brijeshpoojary** [comment]
Ems is updated with the new schools now. The counts were not matching because 58 schools of gka phase 1 & phase 2 were not present in EMS. 31 were activated and 27 inserted as new.

`ems=> select count(*) from schools_institution where cat_id in (9,13,14,15) and active=2;
 count 
-------
 44180
`
This has to reflect on unified_db as well. It did not reflect today as the import script had failed. This should reflect tomorrow and the counts will match.

**Comment by shivangi** [comment]
@brijeshpoojary so please check this tomorrow and assign it to Menaka once it matches your count.

**Comment by menakakhare** [comment]
Reviewed
